Universe = vanilla
getenv = True
Executable = run_mesa.sh
Output =/vol/aibn185/data1/jantoniadis/HeCoresCondor/full_grid/3.0000_0.0014_0.0160/condor.out 
Error =/vol/aibn185/data1/jantoniadis/HeCoresCondor/full_grid/3.0000_0.0014_0.0160/condor.err 
Log =/vol/aibn185/data1/jantoniadis/HeCoresCondor/full_grid/3.0000_0.0014_0.0160/condor.log
request_memory = 1 GB
environment = OMP_NUM_THREADS=2;PYTHONBUFFERED=1
request_cpus = 2 

queue 
