Universe = vanilla
getenv = True
Executable = rn 
Output =/Users/janton/mesa-r10398/star/test_suite/cluster/output/3.5000_0.0200_0.0140/condor.out 
Error =/Users/janton/mesa-r10398/star/test_suite/cluster/output/3.5000_0.0200_0.0140/condor.err 
Log =/Users/janton/mesa-r10398/star/test_suite/cluster/output/3.5000_0.0200_0.0140/condor.log 
environment = OMP_NUM_THREADS=1;PYTHONBUFFERED=1
request_cpus = 1 

queue 
